# 默认配置文件
# 天然气管网数值模拟系统配置

# 数据配置
data:
  data_dir: "data"                    # 数据目录路径
  batch_size: 8                      # 批次大小
  num_workers: 4                     # 数据加载进程数
  validation_split: 0.1              # 验证集比例
  shuffle: true                      # 是否打乱训练数据

# 模型配置
model:
  type: "FluidNet"                    # 模型类型: FluidNet, PhysicsInformedNet, AttentionFluidNet
  
  # FluidNet 配置
  hidden_dims: [512, 256, 128]       # 隐藏层维度
  dropout_rate: 0.1                  # Dropout比例
  activation: "relu"                  # 激活函数: relu, gelu, leaky_relu, elu
  
  # PhysicsInformedNet 配置
  physics_weight: 0.1                # 物理约束权重
  
  # AttentionFluidNet 配置
  hidden_dim: 256                    # Transformer隐藏维度
  num_heads: 8                       # 注意力头数
  num_layers: 4                      # Transformer层数

# 训练配置
training:
  epochs: 100                        # 训练轮数
  log_interval: 10                   # 日志输出间隔
  save_interval: 20                  # 模型保存间隔
  
  # 优化器配置
  optimizer:
    type: "adamw"                    # 优化器类型: adamw, adam, sgd, rmsprop
    learning_rate: 0.001             # 学习率
    weight_decay: 0.0001            # 权重衰减
    betas: [0.9, 0.999]             # Adam beta参数
    momentum: 0.9                    # SGD动量参数
  
  # 学习率调度器配置
  scheduler:
    type: "cosine"                   # 调度器类型: cosine, step, multistep, plateau, warmup_cosine
    T_max: 100                       # 余弦退火周期
    eta_min: 0                       # 最小学习率
    step_size: 30                    # StepLR步长
    gamma: 0.1                       # 学习率衰减因子
    milestones: [50, 80]             # MultiStepLR里程碑
    patience: 10                     # ReduceLROnPlateau耐心值
    warmup_epochs: 10                # WarmupCosine预热轮数
  
  # 损失函数配置
  loss:
    type: "combined"                 # 损失函数类型: fluid, physics, combined
    loss_type: "mse"                 # 基础损失类型: mse, mae, smooth_l1, huber
    physics_weight: 0.1              # 物理约束权重
    output_weights:                  # 各输出文件权重
      "B.csv": 1.0
      "T&E.csv": 1.5
      "H.csv": 1.0
      "C.csv": 1.2
      "N.csv": 1.0
      "R.csv": 1.1
      "P.csv": 1.0
  
  # 早停配置
  early_stopping:
    patience: 15                     # 早停耐心值
    min_delta: 0.000001             # 最小改善阈值
    restore_best_weights: true       # 是否恢复最佳权重

# 推理配置
inference:
  batch_size: 32                     # 推理批次大小
  uncertainty_samples: 100          # 不确定性采样次数
  enable_dropout: true               # 是否启用Monte Carlo Dropout

# 路径配置
paths:
  checkpoints_dir: "checkpoints"     # 模型检查点目录
  logs_dir: "logs"                   # 日志目录
  results_dir: "results"             # 结果输出目录
  plots_dir: "plots"                 # 图表输出目录

# 设备配置
device: "auto"                       # 计算设备: auto, cpu, cuda
random_seed: 42                      # 随机种子

# 可视化配置
visualization:
  plot_training_curves: true         # 是否绘制训练曲线
  plot_predictions: true             # 是否绘制预测结果
  plot_distributions: true           # 是否绘制分布图
  max_plot_points: 10000            # 最大绘制点数
  figure_dpi: 300                    # 图像DPI
  figure_format: "png"               # 图像格式

# 评估配置
evaluation:
  metrics: ["mse", "mae", "r2", "mape"]  # 评估指标
  create_report: true                     # 是否生成评估报告
  save_predictions: true                  # 是否保存预测结果
  
# 高级配置
advanced:
  gradient_clipping: 1.0             # 梯度裁剪阈值
  mixed_precision: false             # 是否使用混合精度
  compile_model: false               # 是否编译模型（PyTorch 2.0+）
  profile_training: false            # 是否分析训练性能

# 实验配置
experiment:
  name: "fluid_simulation"           # 实验名称
  version: "1.0"                     # 版本号
  description: "天然气管网数值模拟实验"  # 实验描述
  tags: ["fluid", "pinn", "simulation"]  # 实验标签